version: '3.9'
services:


  spring_cloud:
     build:
       context: .
       dockerfile: ./dockerFile
     networks:
       web:
         ipv4_address: 172.16.238.5
     ports:
       - '8050:8050'


networks:
  web:
    driver: bridge
    name: web
    ipam:
      driver: default
      config:
        - subnet: 172.16.238.0/24
          gateway: 172.16.238.1
